// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxuqe9Uu2ELy3alxvbRSv5thSeY-MJqoU',
    appId: '1:429901131285:web:649afcac021c193b8f681c',
    messagingSenderId: '429901131285',
    projectId: 'fir-flutter-codelab-2b817',
    authDomain: 'fir-flutter-codelab-2b817.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-2b817.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvLuLMxOLVEcN_np9n10fkkguyGcHb4ec',
    appId: '1:429901131285:android:f2a3b5cd1ec4d3ba8f681c',
    messagingSenderId: '429901131285',
    projectId: 'fir-flutter-codelab-2b817',
    storageBucket: 'fir-flutter-codelab-2b817.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW3D-W3_sr6sfoFB8jACR88FbgMaBRuVQ',
    appId: '1:429901131285:ios:dcedec012bb8dd6a8f681c',
    messagingSenderId: '429901131285',
    projectId: 'fir-flutter-codelab-2b817',
    storageBucket: 'fir-flutter-codelab-2b817.appspot.com',
    iosClientId: '429901131285-mpjvpbj4a79mqu09aqe12r3k0de42l11.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW3D-W3_sr6sfoFB8jACR88FbgMaBRuVQ',
    appId: '1:429901131285:ios:dcedec012bb8dd6a8f681c',
    messagingSenderId: '429901131285',
    projectId: 'fir-flutter-codelab-2b817',
    storageBucket: 'fir-flutter-codelab-2b817.appspot.com',
    iosClientId: '429901131285-mpjvpbj4a79mqu09aqe12r3k0de42l11.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
